#ifndef SERIAL_MSG_HEADER
#define SERIAL_MSG_HEADER

// Setup Constants 

#define BAUD_RATE 9600
// Message Constants 

#define MSG_SIZE 1
#define MSG_SENT -86
#define STOP 0
#define MOVE_FORWARD_ANALOG 1
#define MOVE_BACKWARD_ANALOG 2
#define TURN_LEFT_ANALOG 3
#define TURN_RIGHT_ANALOG 4
#define SET_LINEAR_VELOCITY 5
#define SET_ANGULAR_VELOCITY 6
#define SET_P 8
#define SET_I 9
#define SET_D 10
#define GET_P 11
#define GET_I 12
#define GET_D 13
#define GET_RIGHT_CONTROL 14
#define GET_LEFT_CONTROL 15
#define GET_LINEAR_VELOCITY 20
#define GET_ANGULAR_VELOCITY 21
#define GET_BATTERY 30
#define GET_STATE 31
#define REPORTING_VELOCITY 110
#define REPORTING_ANGULAR_VELOCITY 111
#define REPORTING_L_ANGULAR_VELOCITY 112
#define REPORTING_R_ANGULAR_VELOCITY 113
#define REPORTING_R_CONTROL 114
#define REPORTING_L_CONTROL 115
#define REPORTING_R_C_DEST 116
#define REPORTING_L_C_DEST 117
#define REPORTING_STATE 122
#define REPORTING_P 123
#define REPORTING_I 124
#define REPORTING_D 125
#define REPORTING_BATTERY 127

#endif